### DISCUSSION TITLE
Prototype proposal for 2a

### DISCUSSION THREAD

**Discussion by davidradl** [odpi/egeria#7502] [Ideas]
@lpalashevski @planetf1  (@juergenhemelt I cant see Taylans id to add him here)   

Relating to https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=70648184 item 2a. I have been thinking about the prototype:

Phase 1:
- Make changes in the main Egeria repo.
- Create a new application similar to server chassis, called server-standalone (fyi I create the ui chassis so have some familiarity with this approach)
    - Change the grade file to not being in any admin projects. So that we have no admin endpoints picked up by spring.
    -  Duplicate the code in https://github.com/odpi/egeria/blob/main/open-metadata-implementation/admin-services/admin-services-server/src/main/java/org/odpi/openmetadata/adminservices/server/OMAGServerOperationalServices.java into a new project maybe called standaloneServerLifecycle. This new project would pick up the config from the file system, based on an environment variable. It will assume there is a data folder with a server and platforms folders already there.
    - Need to ensure that the server is created after what ever initialisation has occurred when the process starts 
    - Decide if we want to separate the read only storage from the cohort registry storage writeable. 
   - We could assume that the config is encrypted (or plain text) , or pass the config store connector name through to use in an environment variable . I think for a prototype using the encrypted default would make sense for now - as it is a default. We can change as required. 
    - Assumptions
        - No new rest calls 
        - No platform changes
        - No change to tenancy

Phase 2:
	- Investigate removing the platform services and feeding through the platform information using the file system or environment variables. 

Phase 3:
       - investigate / agree whether config maps or environment variables are better ways to pass config and platform information  
	 
Phase 4:
       - add shutdown and status rest endpoints. Hopefully we understand more about what the status will / should mean after having done phase 1 and 2. 
       - 
Phase 5:
	- remove the need for any tenancy logic. 

I can have a play with phase 1 early next week, if we think this is a reasonable plan.

**Comment by juergenhemelt** [comment]
fyi @T4ylan

**Comment by juergenhemelt** [comment]
@davidradl 
I suggest the server configuration to be part of the Spring application properties. So you could use Spring  mechanisms to pass the configuration - e. g. environment variables, properties/yaml-file, command line arguments.

**Reply by davidradl** [reply]
@juergenhemelt

 I think the idea is that the file containing the config would be written into K8s config maps, and we could use the existing config store connectors mechanisms to pick up the config. I do not know the pros and cons of config maps vs specifying in yaml CRD / environment variables . How would the java app pick up the yaml content?

Are you thinking that there is in environment variable with a complete config  as its value?   

Maybe there is a phase 1.5 or 2.5 to assess passing config and optimizing existing config

**Reply by juergenhemelt** [reply]
I am thinking about an externalized configuration as described here: https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config
This is already part of the startup configuration of Egeria: https://egeria-project.org/guides/admin/configuring-the-omag-server-platform/?h=#applicationproperties
Why not extend this by properties like this:
```yaml
startup:
  server:
    class: IntegrationServiceRequestBody
    omagserverPlatformRootURL: "{{mds-baseURL}}"
    omagserverName: "{{mds-server}}"
    connectorUserId: "{{user}}"
    integrationConnectorConfigs:
    - class: IntegrationConnectorConfig
      connectorName: LineageReplicationIntegrator
      typeName: Lineage Replication Integration Connector
      connection:
        class: VirtualConnection
        qualifiedName: replication-1
        connectorType:
          class: ConnectorType
          connectorProviderClassName: org.odpi.openmetadata.adapters.connectors.integration.lineage.sample.SampleLineageEventReceiverIntegrationProvider
        embeddedConnections:
        - class: EmbeddedConnection
          embeddedConnection:
            class: Connection
            qualifiedName: repnest-etu
            connectorType:
              class: ConnectorType
              connectorProviderClassName: org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicProvider
            endpoint:
              class: Endpoint
              headerVersion: 0
              address: "{{topic-name}}"
            configurationProperties:
              local.server.id: "{{consumerid}}"
              consumer:
                bootstrap.servers: "{{kafkaep}}"
                ssl.keystore.location: "{{keystore-location}}"
                ssl.keystore.password: "{{keystore-password}}"
                ssl.truststore.location: "{{truststore-location}}"
                ssl.truststore.password: "{{truststore-password}}"
                auto.offset.reset: earliest
                security.protocol: SSL
              producer:
                bootstrap.servers: "{{kafkaep}}"
                ssl.keystore.location: "{{keystore-location}}"
                ssl.keystore.password: "{{keystore-password}}"
                ssl.truststore.location: "{{truststore-location}}"
                ssl.truststore.password: "{{truststore-password}}"
                security.protocol: SSL
      metadataSourceQualifiedName: lineage-replication-1
      refreshTimeInterval: '1'
      permittedSynchronization: FROM_THIRD_PARTY
```

In Kubernetes you can put this piece of YAML in a ConfigMap and either mount it as a file or use it as an environment variable.
