### ISSUE TITLE
Compliance test support in vdc helm chart doesn't respect configured repomode

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1624]
Running the CTS in the egeria vdc helm chart i noticed that the repomode (in-memory or graph) configured in the user configuration is not respected.

A fix was needed to correctly configure the cts server with the repomode configured

Once done the key elements are:
In an overriding values file:
```
cts:
  enabled: true
egeria:
  #repomode: local-graph-repository
  repomode: in-memory-repository
```

And to get the results use the client, or a tool like http (nicer output than curl)with something like:
```
http --pretty format GET http://egeriadev.mydomain.net:NNNNN/servers/cts/open-metadata/conformance-suite/users/myuser/report
```
