### ISSUE TITLE
Azure pipeline docker builds running against dependabot branches

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1785]
Docker builds are currently running against dependabot branches, which is causing the images written to dockerhub to be overwritten by the latest dependabot created branch - rather than master.

Dependabot creates new branches dynamically to test proposed dependencies

The branches being built are shown at
https://dev.azure.com/odpi/Egeria/_build?definitionId=13&_a=summary&view=branches

This issue will tactically address ensuring that dependabot builds don't run/publish

Looking at the azure pipeline definition for docker I see
```
schedules:
  - cron: "11 0 * * *"
    displayName: Daily Docker Build
    always: true
    branches:
      include:
        - master
```
which looks correct, so I am unsure why the other branches are being built in this case

See also #1595 (which should  allow branch specific images) #1630 (publishing only to jfrog rather than dockerhub) 

Any idea @bramwelt

**Comment by bramwelt** [comment]
Looks like the issue is the merge trigger:
```
  trigger:
    paths:
      include:
        - open-metadata-resources/open-metadata-deployment/docker
```
This will run against merges to _any_ branch that modifies those paths. Adding the restriction of:
```
    branches:
      include:
        - master
```
should fix this.
