### ISSUE TITLE
Egeria UI Stuck in Container Create State --- Error response from daemon: OCI runtime create failed

### ISSUE THREAD

**Issue by jried31** [odpi/egeria#2263]
To whom this may concern,
The Egeria UI pod remains in ContainerCreating state with no further log information. Is it possible to assist?

I attempted to give the system more resources but it's not solving the problem.

The error message is:
`Warning  FailedCreatePodSandBox  69s (x8 over 77s)  kubelet, 9.4.174.97  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "frank-odpi-egeria-vdc-ui-564564df49-r5qtr": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"read init-p: connection reset by peer\"": unknown`

**Comment by cmgrote** [comment]
@planetf1 is this part of what you're already investigating on the UI side?

**Comment by planetf1** [comment]
Hi @cmgrote, nope - well not get. But indeed there was a recently fixed issue that broke the UI

This was addressed in #2114 - see https://github.com/odpi/egeria/commit/12c1e36b13c834118ff39889e7a5f56b2e5dabf4

so it should be fine in current docker images/charts

@jried31 Can you do a `kubectl describe pod/frank-odpi-egeria-vdc-ui-564564df49-r5qtr` I'm intrigued to see what else you see. And also a 'kubectl logs frank-odpi-egeria-vdc-ui-564564df49-r5qtr'. 

Can you also confirm how recent code you are using for both egeria, and for the ibm-igc connector. Also that you are using up to date fork of your own, or directly the odpi repos.

**Comment by jried31** [comment]
Output of kubectl describe pod...
`Warning  FailedCreatePodSandBox  2m8s (x4465 over 112m)  kubelet, 9.4.174.97  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "frank-odpi-egeria-vdc-ui-564564df49-r5qtr": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"read init-p: connection reset by peer\"": unknown`

Kubectl logs has nothing as pod hasnt started.

**Comment by planetf1** [comment]
I would expect much more output from describe ie
```
➜  user-interfaces git:(davidradl-git1942) kubectl describe pod/lab-kafka-0
Name:         lab-kafka-0
Namespace:    egeria
Priority:     0
Node:         10.72.127.138/10.72.127.138
Start Time:   Fri, 13 Dec 2019 12:45:56 +0000
Labels:       app.kubernetes.io/component=kafka
              app.kubernetes.io/instance=lab
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kafka
              controller-revision-hash=lab-kafka-7b9697db44
              helm.sh/chart=kafka-6.1.6
              statefulset.kubernetes.io/pod-name=lab-kafka-0
Annotations:  kubernetes.io/psp: ibm-privileged-psp
Status:       Running
```
is just the first few lines from a describe on my kafka port.

Is that the full output? What is your k8s environment? Have you issues with multiple pods? Can you clarify the versions of containers & charts you are using, and whether your github fork is up to date.

The error itself looks as if it could relate to an issue with your kubernetes environment in general. Are you able to deploy other helm or otherwise create pods? Are you running out of resources perhaps?

**Comment by planetf1** [comment]
The UI deployment is reporting
```
status:
  conditions:
  - lastTransitionTime: "2019-12-12T23:23:24Z"
    lastUpdateTime: "2019-12-12T23:23:24Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2019-12-17T19:20:52Z"
    lastUpdateTime: "2019-12-17T19:20:52Z"
    message: 'pods "frank-odpi-egeria-vdc-ui-79dbd7678f-qm7rt" is forbidden: exceeded
      quota: compute, requested: requests.cpu=50m, used: requests.cpu=500m, limited:
      requests.cpu=500m'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  - lastTransitionTime: "2019-12-17T19:36:29Z"
    lastUpdateTime: "2019-12-17T19:36:29Z"
    message: ReplicaSet "frank-odpi-egeria-vdc-ui-79dbd7678f" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 5
  replicas: 1
  unavailableReplicas: 2
```

This is a quota issue - perhaps for the namespace.

As such this looks like a user/infrastructure issue. Please do comment/reopen if you have any suggestions for docs or yaml improvements - but broadly this seems to be BAU k8s.
