### ISSUE TITLE
IGC connector not loading - user/env error - improve audit msgs

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2348]
Using the odpi-egeria-vdc helm chart with the following override
ie
```
helm install vdc odpi-egeria-vdc -f ~/etc/cloud_igc.yaml
```
where the yaml contains: (hostname/ip obfuscated)
```
ibmigc:
  enabled: true
  internal:
    enabled: false
  external:
    enabled: true
    ip: "111.222.333.444"
    hostname: "igc.openmetadata.mydomain.com"
    ports:
      https: "9446"
      broker: "59092"
```
results in all the pods etc starting up. However the IGC proxy fails to initialize correctly with:
```
Fri Jan 03 14:31:48 GMT 2020 ibmigc Exception OMRS-AUDIT-0035 The connector to the local repositorys event mapper failed with a {0} exception and the following error message: {1}
```

Two issues here
 a) The audit message is incorrectly formatted - preventing customer PD
 b) Why the actual failure

The same error was reported  on slack at https://odpi.slack.com/archives/CBPRDQPRC/p1578028854030200 -- this was running locally, not using containers. I tried the helm chart to get my own environment working for debugging and comparison.
