### ISSUE TITLE
UI is broken in container environment

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2350]
Running master & going to the UI page

* docker-compose - https://localhost:18443
* openshift 4 - https://console-openshift-console.example.com:30443
results in

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Jan 03 15:19:39 GMT 2020
There was an unexpected error (type=Not Found, status=404).
No message available
```

**Comment by planetf1** [comment]
The UI *does* render locally

Suspect this may have been broken by recent UI refactoring / un-refactoring ...

**Comment by planetf1** [comment]
DEBUG log is at https://gist.github.com/20543300e90f50bf402c939362a31230
includes
```
2020-01-07 15:39:56.211 DEBUG 1 --- [nio-8443-exec-2] pertySourcedRequestMappingHandlerMapping : looking up handler for path: /
2020-01-07 15:39:56.222 DEBUG 1 --- [nio-8443-exec-2] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped to ResourceHttpRequestHandler ["classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/", "/"]
2020-01-07 15:39:56.225 DEBUG 1 --- [nio-8443-exec-2] o.j.s.OpenEntityManagerInViewInterceptor : Opening JPA EntityManager in OpenEntityManagerInViewInterceptor
2020-01-07 15:39:56.227 DEBUG 1 --- [nio-8443-exec-2] o.s.w.s.r.ResourceHttpRequestHandler     : Resource not found
2020-01-07 15:39:56.227 DEBUG 1 --- [nio-8443-exec-2] o.j.s.OpenEntityManagerInViewInterceptor : Closing JPA EntityManager in OpenEntityManagerInViewInterceptor
2020-01-07 15:39:56.227 DEBUG 1 --- [nio-8443-exec-2] o.s.web.servlet.DispatcherServlet        : Completed 404 NOT_FOUND
```

**Comment by planetf1** [comment]
Full debug log including component scan -> https://gist.github.com/4d747c6d6ac7c225355848cd23dacba1

**Comment by planetf1** [comment]
The docker build pulls the UI jar from https://odpi.jfrog.io/odpi/egeria-snapshot/org/odpi/egeria/ui-chassis-spring/1.4-SNAPSHOT/ 
Running this directly even locally demonstrates the same issue as seen in the container environment

**Comment by davidradl** [comment]
In the developer view in chrome, do you have any errors in the console, or failing rest calls? any errors in the OMAGServer?

**Comment by planetf1** [comment]
I should have updated... I made a little progress. It's a build/packaging issue. Does not look like a good issue.

The jar from my local build works fine, as does the jar within the maven artifact in my local .m2 repo
The jar from the official build (from artifactory, within the same named maven artifact) fails

Differences? - artifactory, JRE, javac (both azul - MS default).. 

Will continue to persue tomorrow. Thanks for the offer of help. And no there are no failures on the console. Tomcat is very diligently showing the error page cleanly :-) The debug logs (links above) also show there is simply no matching URL found for / which is very odd.

Will update.

**Comment by planetf1** [comment]
Observed in #2340 - A build of egeria, and executing the UI on a raspberry pi4 also hits the same issue. This was built with openjdk 11 (hotspot). The official build is primarily open jdk8 (azul=ms azure). This could be an OS issue. Will test on Windows also.

**Comment by planetf1** [comment]
With #2388 address, note that the UI does work correctly when built under Windows.

**Comment by planetf1** [comment]
When build under WSL2 (on Windows, but Ubuntu, openjdk 11) - fails with error mapping page

**Comment by planetf1** [comment]
After some more thorough investigation, the issue is that in the broken jars the subdirectory
 - public
is entirely missing.

Thus there is indeed nothing at the / address

The problem is not caused by the java compiler - indeed a build with the azul javac works fine, but rather with packaging.

**Comment by planetf1** [comment]
The current merge build (from where we get te UI image) is built using the pipeline definition in .azure-pipelines/merge.yml which contains this for the actual maven invocation
```
       steps:
          - task: ArtifactoryMaven@1
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              artifactoryResolverService: 'ODPiArtifactory'
              targetResolveReleaseRepo: 'egeria-staging'
              targetResolveSnapshotRepo: 'egeria-snapshot'
              artifactoryDeployService: 'ODPiArtifactory'
              targetDeployReleaseRepo: 'egeria-staging'
              targetDeploySnapshotRepo: 'egeria-snapshot'
              collectBuildInfo: true
              buildName: 'Egeria'
              buildNumber: '$(Build.BuildNumber)'
              includeEnvVars: true
              goals: 'clean install'
              options: >-
                  --batch-mode
                  -e
                  -s .m2/settings.xml
                  -Dmerge
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
                  -P artifactory
```
This uses the ArtifactoryMaven task from the marketplace jfrog plugin v1.8.1 . Fortunately this uses the open source plugin task from https://github.com/jfrog/artifactory-vsts-extension/tree/master/tasks/ArtifactoryMaven

It does not use it's own maven version, but whatever is found on the local vm - in this case whatever Azure provides.

We do override a few maven settings via .m2/settings.xml - mostly relating to repos (for staging and publish). Notably we also do modify where node/npm is retrieved from
```
        <node.downloadRoot>https://odpi.jfrog.io/odpi/nodejs-dist/</node.downloadRoot>
        <npm.downloadRoot>https://odpi.jfrog.io/odpi/npm-dist/</npm.downloadRoot>
```
being a UI build this could be a factor. Though the layout seems just the same as the public repo, and both old versions and the new ones referred to in #2388 are present
