### ISSUE TITLE
vdc helm chart - fails in IBM cloud (403 checking endpoints due to default security policy)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#827]
wait-for-db initialization container can end up in permanent loop if config wrong:

kubectl logs knobby-tapir-vdc-job-01-data-loader-9jpcm -c wait-for-db

waiting for knobby-tapir-vdc-postgresql-service
jq: error (at <stdin>:14): Cannot iterate over null (null)
/check-availability.sh: line 8: [: -ge: unary operator expected
waiting for knobby-tapir-vdc-postgresql-service
jq: error (at <stdin>:14): Cannot iterate over null (null)
/check-availability.sh: line 8: [: -ge: unary operator expected

May relate to credential access or service configuration -- in this case we are checking for status of postgresql

it would seem as if 'available_pods' is evaluating to null

Root cause:
```
bash-4.4# curl -s --cacert $CACERT --header "Authorization: Bearer $token" https://kubernetes.default.svc/api/v1/namespaces/$NAMESPACE/endpoints/$SERVICE
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "endpoints \"knobby-tapir-vdc-postgresql-service\" is forbidden: User \"system:serviceaccount:default:default\" cannot get resource \"endpoints\" in API group \"\" in the namespace \"default\"",
  "reason": "Forbidden",
  "details": {
    "name": "knobby-tapir-vdc-postgresql-service",
    "kind": "endpoints"
  },
  "code": 403
```

**Comment by planetf1** [comment]
will likely need to define role/cluster role rbac for any production k8s environment - default open config may only work with single node dev cluster.

**Comment by planetf1** [comment]
Ref for IBMcloud - https://developer.ibm.com/tutorials/using-kubernetes-rbac-and-service-accounts/
ideally should verify in openshift, azure etc.

**Comment by planetf1** [comment]
I'll work on fixing this on ibmcloud tomorrow

**Comment by cmgrote** [comment]
☹️ yeah, I was guessing if anything wasn't going to be compatible across various cluster setups that would probably be it (+ the `hostPath` thing I mentioned in Amsterdam).  This is the k8s "introspection" I mentioned.

Would be ideal if we can find a way to get it working in other environments with some RBAC config, and keep the local environment super-simple (for maximum experimentation / "try-it-out" uptake), but we could otherwise investigate alternative ways to do the service readiness checks...

**Comment by planetf1** [comment]
Oh yes I agree - we want to cover both the standalone case, and the cloud case.

currently I am using this fragment -- will submit a PR tomorrow when fully tested. i had to make a few other changes to work in public cloud - and still need to verify cluster operation & error handling

However the init pod that was failing now succeeds - the api works

Is this 'harmless' for your environment or do i need to bracket it with a condition?
```
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vdc-api-role
  namespace: {{ Release.namespace }}
  labels:
    app: config-info
rules:
- apiGroups: [""]
  resources: ["endpoints","pods","services"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vdc-api-role-binding
  namespace: {{ Release.namespace }}
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive
  namespace: {{ Release.namespace }}
roleRef:
  kind: Role
  name: vdc-api-role
  apiGroup: rbac.authorization.k8s.io
```
